name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Eigen3
      run: sudo apt-get update && sudo apt-get install -y libeigen3-dev
    - name: Ensure pip is installed
      run: python3 -m ensurepip --upgrade
    - name: Install NumPy for Python3
      run: python3 -m pip install numpy
    - name: Configure CMake
      run: cmake .
    - name: Build
      run: make
